version: '3.8'

services:
  db:
    image: mysql
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - authenticator_data:/var/lib/mysql
    deploy:
      resources:
        limits:
          memory: 512m
        reservations:
          memory: 265m

volumes:
  authenticator_data: