version: '3.8'

services:
  db:
    image: mysql
    container_name: iam_authenticator
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - iam_data:/var/lib/mysql

volumes:
  iam_data: